import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Initialize Firebase for the app.
///
/// In production, you should provide platform-specific options:
/// - Android: google-services.json
/// - iOS: GoogleService-Info.plist
/// - Web: firebase_options.dart generated by FlutterFire CLI
Future<void> initializeFirebase() async {
  if (Firebase.apps.isNotEmpty) return;

  try {
    if (kIsWeb) {
      await Firebase.initializeApp(
        options: const FirebaseOptions(
          apiKey: 'YOUR_API_KEY',
          appId: 'YOUR_APP_ID',
          messagingSenderId: 'YOUR_SENDER_ID',
          projectId: 'YOUR_PROJECT_ID',
        ),
      );
    } else {
      await Firebase.initializeApp();
    }
  } catch (e) {
    // Firebase initialization failed - continue without it in development
    debugPrint('Firebase initialization failed: $e');
  }
}

/// Placeholder for generated firebase_options.dart
///
/// Run `flutterfire configure` to generate this file with real credentials.
/// The generated file will have platform-specific options for Android, iOS, Web.
class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
  );
}